name: gdi-sars-cov-2
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - openssl
  - iqtree
  - python=3.8
  - seaborn
  - pymongo
  - bedtools
  - pyqt
  - r-irkernel
  - htslib
  - pip
  - snpeff
  - r-phangorn
  - certifi
  - r-ape
  - bioconductor-rhtslib
  - sqlalchemy[version='>=1.4']
  - matplotlib
  - jupyterlab
  - r-phytools
  - bcftools
  - ca-certificates
  - papermill
