name: gdi-simulation
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - r-ape
  - snpeff
  - htslib[version='>=1.13']
  - jupyterlab
  - matplotlib
  - pip
  - pyqt
  - r-phytools
  - sqlalchemy[version='>=1.4']
  - python=3.8
  - bioconductor-rhtslib
  - bedtools
  - r-irkernel
  - pymongo
  - iqtree
  - r-phangorn
  - bcftools[version='>=1.13']
  - papermill
  - ca-certificates
  - certifi
  - openssl
  - udunits2
  - r-sf
  - seaborn
  - minimap2==2.22
  - setuptools=57
  - samtools[version='>=1.13']
  - bamtools
