name: gdi-simulation
channels:
  - conda-forge
  - r
  - bioconda
  - defaults
dependencies:
  - r-ape
  - snpeff
  - htslib
  - jupyterlab
  - matplotlib
  - pip
  - pyqt
  - r-phytools
  - sqlalchemy[version='>=1.4']
  - python=3.8
  - bioconductor-rhtslib
  - bedtools
  - r-irkernel
  - pymongo
  - iqtree
  - r-phangorn
  - bcftools
  - papermill
  - ca-certificates
  - certifi
  - openssl
  - udunits2
  - r-sf
  - seaborn
  - pip:
    - genomics-data-index
    - cmdbench
